name: dart_cognitive_complexity
description: A cognitive complexity linter for Dart libraries or applications.
version: 2.0.0
repository: https://github.com/oursky/dart_cognitive_complexity

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ^13.0.0
  analysis_server_plugin: ^0.3.0
  path: ^1.9.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.21.0
